# Generated by Django 3.1.1 on 2021-02-02 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cadres_cluster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drugs', '0005_auto_20210201_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contra_indicated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.generic')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='users.facility')),
                ('generic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_drug_interactions', to='drugs.generic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interactions',
            },
        ),
        migrations.DeleteModel(
            name='DrugInteraction',
        ),
        migrations.AddConstraint(
            model_name='interactions',
            constraint=models.UniqueConstraint(fields=('generic', 'contra_indicated'), name='Drug cannot be contraindicated with itself'),
        ),
    ]
